language: node_js
node_js: 14 
cache: npm
install:
  - npm install
services:
  - xvfb
before_script:
  - "export DISPLAY=:99.0"
script:
  - npm test
  - CI=false npm run build
after_success:
  - npm run coverage